# Generated by Django 5.1.2 on 2024-10-28 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.CharField(max_length=30, primary_key='uid', serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('loanamount', models.IntegerField()),
                ('dob', models.DateField()),
                ('age', models.IntegerField()),
            ],
        ),
    ]
